// Code generated by protoc-gen-go. DO NOT EDIT.
// source: erpc.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RequestContext struct {
	Service              string   `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	Input                string   `protobuf:"bytes,2,opt,name=input,proto3" json:"input,omitempty"`
	Header               string   `protobuf:"bytes,3,opt,name=header,proto3" json:"header,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestContext) Reset()         { *m = RequestContext{} }
func (m *RequestContext) String() string { return proto.CompactTextString(m) }
func (*RequestContext) ProtoMessage()    {}
func (*RequestContext) Descriptor() ([]byte, []int) {
	return fileDescriptor_b49f2b3f3260770b, []int{0}
}

func (m *RequestContext) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestContext.Unmarshal(m, b)
}
func (m *RequestContext) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestContext.Marshal(b, m, deterministic)
}
func (m *RequestContext) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestContext.Merge(m, src)
}
func (m *RequestContext) XXX_Size() int {
	return xxx_messageInfo_RequestContext.Size(m)
}
func (m *RequestContext) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestContext.DiscardUnknown(m)
}

var xxx_messageInfo_RequestContext proto.InternalMessageInfo

func (m *RequestContext) GetService() string {
	if m != nil {
		return m.Service
	}
	return ""
}

func (m *RequestContext) GetInput() string {
	if m != nil {
		return m.Input
	}
	return ""
}

func (m *RequestContext) GetHeader() string {
	if m != nil {
		return m.Header
	}
	return ""
}

type ResponseContext struct {
	Status               int32    `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Header               string   `protobuf:"bytes,2,opt,name=header,proto3" json:"header,omitempty"`
	Result               string   `protobuf:"bytes,3,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResponseContext) Reset()         { *m = ResponseContext{} }
func (m *ResponseContext) String() string { return proto.CompactTextString(m) }
func (*ResponseContext) ProtoMessage()    {}
func (*ResponseContext) Descriptor() ([]byte, []int) {
	return fileDescriptor_b49f2b3f3260770b, []int{1}
}

func (m *ResponseContext) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResponseContext.Unmarshal(m, b)
}
func (m *ResponseContext) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResponseContext.Marshal(b, m, deterministic)
}
func (m *ResponseContext) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResponseContext.Merge(m, src)
}
func (m *ResponseContext) XXX_Size() int {
	return xxx_messageInfo_ResponseContext.Size(m)
}
func (m *ResponseContext) XXX_DiscardUnknown() {
	xxx_messageInfo_ResponseContext.DiscardUnknown(m)
}

var xxx_messageInfo_ResponseContext proto.InternalMessageInfo

func (m *ResponseContext) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *ResponseContext) GetHeader() string {
	if m != nil {
		return m.Header
	}
	return ""
}

func (m *ResponseContext) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

func init() {
	proto.RegisterType((*RequestContext)(nil), "pb.RequestContext")
	proto.RegisterType((*ResponseContext)(nil), "pb.ResponseContext")
}

func init() { proto.RegisterFile("erpc.proto", fileDescriptor_b49f2b3f3260770b) }

var fileDescriptor_b49f2b3f3260770b = []byte{
	// 183 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x8f, 0x31, 0x8b, 0x83, 0x40,
	0x10, 0x46, 0x51, 0x51, 0xb9, 0x29, 0xee, 0x60, 0xee, 0x90, 0xe5, 0xaa, 0x60, 0x95, 0xca, 0xc2,
	0x54, 0xa9, 0xfd, 0x03, 0x61, 0xab, 0xa4, 0x54, 0x33, 0x10, 0x21, 0xb8, 0x9b, 0x9d, 0xd9, 0x90,
	0x9f, 0x1f, 0xb2, 0x2a, 0x68, 0xf9, 0x5e, 0xf1, 0xf8, 0x3e, 0x00, 0x72, 0xb6, 0xaf, 0xac, 0x33,
	0x62, 0x30, 0xb6, 0x5d, 0x79, 0x86, 0x6f, 0x4d, 0x0f, 0x4f, 0x2c, 0x8d, 0x19, 0x85, 0x5e, 0x82,
	0x0a, 0x72, 0x26, 0xf7, 0x1c, 0x7a, 0x52, 0xd1, 0x2e, 0xda, 0x7f, 0xe9, 0x05, 0xf1, 0x0f, 0xd2,
	0x61, 0xb4, 0x5e, 0x54, 0x1c, 0xfc, 0x04, 0x58, 0x40, 0x76, 0xa3, 0xf6, 0x4a, 0x4e, 0x25, 0x41,
	0xcf, 0x54, 0x5e, 0xe0, 0x47, 0x13, 0x5b, 0x33, 0x32, 0x2d, 0xe9, 0x02, 0x32, 0x96, 0x56, 0x3c,
	0x87, 0x72, 0xaa, 0x67, 0x5a, 0x25, 0xe2, 0x75, 0xe2, 0xe3, 0x1d, 0xb1, 0xbf, 0xcb, 0x92, 0x9e,
	0xa8, 0x3e, 0x42, 0xa2, 0x4f, 0x0d, 0xd6, 0x90, 0xcf, 0xdb, 0x11, 0x2b, 0xdb, 0x55, 0xdb, 0x23,
	0xff, 0xbf, 0x93, 0xdb, 0x4c, 0xe8, 0xb2, 0x70, 0xfd, 0xf0, 0x0e, 0x00, 0x00, 0xff, 0xff, 0x0a,
	0x5f, 0xb2, 0xe1, 0x08, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// RPCClient is the client API for RPC service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RPCClient interface {
	Request(ctx context.Context, in *RequestContext, opts ...grpc.CallOption) (*ResponseContext, error)
}

type rPCClient struct {
	cc *grpc.ClientConn
}

func NewRPCClient(cc *grpc.ClientConn) RPCClient {
	return &rPCClient{cc}
}

func (c *rPCClient) Request(ctx context.Context, in *RequestContext, opts ...grpc.CallOption) (*ResponseContext, error) {
	out := new(ResponseContext)
	err := c.cc.Invoke(ctx, "/pb.RPC/Request", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RPCServer is the server API for RPC service.
type RPCServer interface {
	Request(context.Context, *RequestContext) (*ResponseContext, error)
}

// UnimplementedRPCServer can be embedded to have forward compatible implementations.
type UnimplementedRPCServer struct {
}

func (*UnimplementedRPCServer) Request(ctx context.Context, req *RequestContext) (*ResponseContext, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Request not implemented")
}

func RegisterRPCServer(s *grpc.Server, srv RPCServer) {
	s.RegisterService(&_RPC_serviceDesc, srv)
}

func _RPC_Request_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestContext)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RPCServer).Request(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.RPC/Request",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RPCServer).Request(ctx, req.(*RequestContext))
	}
	return interceptor(ctx, in, info, handler)
}

var _RPC_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.RPC",
	HandlerType: (*RPCServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Request",
			Handler:    _RPC_Request_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "erpc.proto",
}
